# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = org.metooo
archives_base_name = chunkdebugtool

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.12.2
loader_version = 0.19.2
osl_version = 0.17.2
feather_build = 1
raven_build = 1
sparrow_build = 1
